
FROM oven/bun:alpine

WORKDIR /app


COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./packages/libs ./packages/libs
COPY ./packages/validator ./packages/validator
COPY ./packages/eslint-config ./packages/eslint-config
COPY ./packages/typescript-config ./packages/typescript-config

COPY ./apps/server/package.json ./apps/server/package.json
COPY ./apps/server/bun.lock ./apps/server/bun.lock

RUN bun install

COPY ./apps/server ./apps/server

EXPOSE 3001

CMD [ "bun","run","docker:server" ]